# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Swarm FAC Exploration
author: "Adrian Blagau et al."
logo: ""
only_build_toc_files: true

execute:
  execute_notebooks: force
  timeout: 120

launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url            : "https://vre.vires.services"
  binderhub_url             : ""

repository:
  url: https://github.com/Swarm-DISC/FAC_exploration
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button      : false
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  home_page_in_navbar       : true
  comments:
    hypothesis              : true
