channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pre-commit
  - ipykernel
  - numpy=1.21.5
  - pandas=1.4.1
  - scipy=1.8.0
  - matplotlib=3.5.1
  - ipympl=0.8.8
  - jupyter-book=0.12.1
  - pip:
    - viresclient==0.10.1
