channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - pip
  - pre-commit
  - numpy=1.20.2
  - pandas=1.2.3
  - scipy=1.6.2
  - matplotlib=3.4.1
  - jupyter-book=0.12.1
  - pip:
    - viresclient==0.10.0